name: iremember
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.2
  firebase_storage: ^4.0.1
  get: ^3.4.1
  get_it: ^5.0.0
  image: ^2.1.18
  image_cropper: ^1.3.1
  uuid: ^2.2.2
  image_picker: ^0.6.7+21
  path_provider: ^1.6.27

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
